//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stroymaterials.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id_orders { get; set; }
        public int orders_pointup { get; set; }
        public int orders_users { get; set; }
        public int orders_check { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Pointup Pointup { get; set; }
        public virtual Users Users { get; set; }
    }
}
